// DANS LE CADRE DE CET EXERCICE J'AI PRIS LE CHOIX DE LE PLACER DANS LE DOSSIER SOURCE DU SYSTEME POUR FACILITER LA COMPREHENSION
// MAIS NORMALEMENT CE FICHIER EST STOCKE SUR UN SERVEUR SECURISE
export const jwtConstants = {
    secret: 'secretKey',
};    